const STORAGE_MEMBERS = 'kakao-assignment-members-v1';
const STORAGE_SUBMISSIONS = 'kakao-assignment-submissions-v1';
const DEFAULT_MEMBER_NAMES = ['강보람', '김남희', '김보영', '김수경', '남수현', '민경', '박윤희', '백근혜', '서윤정', '신봉일', '안태욱', '양소희', '오동민', '오혜숙', '오희주', '이경훈', '이길례', '장소향', '정유진', '조영임', '주영순', '최진웅', '한재림', '홍민지', '황주애'];
const $ = id => document.getElementById(id);
let members = loadMembers();
let submissions = loadSubmissions();

function newId() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
function loadMembers() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_MEMBERS)); if (Array.isArray(saved)) return saved; } catch {} return DEFAULT_MEMBER_NAMES.map(name => ({ id: newId(), name, aliases: [] })); }
function loadSubmissions() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_SUBMISSIONS)); return Array.isArray(saved) ? saved : []; } catch { return []; } }
function saveMembers() { localStorage.setItem(STORAGE_MEMBERS, JSON.stringify(members)); }
function saveSubmissions() { localStorage.setItem(STORAGE_SUBMISSIONS, JSON.stringify(submissions)); }
function dateKey(date = new Date()) { const y = date.getFullYear(); const m = String(date.getMonth() + 1).padStart(2, '0'); const d = String(date.getDate()).padStart(2, '0'); return `${y}-${m}-${d}`; }
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value ?? ''; return el.innerHTML; }
function formatDateTime(value) { return new Intl.DateTimeFormat('ko-KR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)); }
function memberName(id) { return members.find(m => m.id === id)?.name || '삭제된 회원'; }
function showNotice(text, type = 'error') { $('submitNotice').textContent = text; $('submitNotice').className = `notice ${type}`; }
function renderSubmitterOptions() { const current = $('submitter').value; $('submitter').innerHTML = '<option value="">이름을 선택하세요</option>' + members.map(m => `<option value="${m.id}">${escapeHtml(m.name)}</option>`).join(''); if (members.some(m => m.id === current)) $('submitter').value = current; }
function renderHistory() {
  const day = $('historyDate').value || dateKey(); const daySubmissions = submissions.filter(s => s.date === day); const byMember = members.map(member => ({ member, submission: daySubmissions.find(s => s.memberId === member.id) })); const submitted = byMember.filter(x => x.submission).length; const total = members.length; const rate = total ? Math.round(submitted / total * 100) : 0;
  $('totalCount').textContent = total; $('submittedCount').textContent = submitted; $('missingCount').textContent = total - submitted; $('rateText').textContent = `${rate}%`; $('progressBar').style.width = `${rate}%`; $('historyTitle').textContent = `${day} 제출 현황`; $('historyDescription').textContent = daySubmissions.length ? `${daySubmissions.length}명의 제출 기록이 있습니다.` : '이 날짜에는 제출 기록이 없습니다.';
  $('historyBody').innerHTML = byMember.length ? byMember.map(({ member, submission }) => `<tr><td><strong>${escapeHtml(member.name)}</strong></td><td><span class="badge ${submission ? 'done' : 'miss'}">${submission ? '제출완료' : '미제출'}</span></td><td>${submission ? formatDateTime(submission.submittedAt) : '—'}</td><td>${submission ? `<a href="${escapeHtml(submission.url)}" target="_blank" rel="noopener">결과물 열기 ↗</a>` : '—'}</td><td class="evidence">${submission ? escapeHtml(submission.note || '—') : '—'}</td></tr>`).join('') : '<tr><td colspan="5" class="empty">등록된 회원이 없습니다.</td></tr>';
  renderRecent();
}
function renderRecent() { const recent = [...submissions].sort((a, b) => new Date(b.submittedAt) - new Date(a.submittedAt)).slice(0, 30); $('recentList').innerHTML = recent.length ? recent.map(s => `<div class="recent-row"><span><strong>${escapeHtml(memberName(s.memberId))}</strong><small>${escapeHtml(s.date)} · ${formatDateTime(s.submittedAt)}</small></span><a href="${escapeHtml(s.url)}" target="_blank" rel="noopener">${escapeHtml(s.url)}</a></div>`).join('') : '<p class="empty-box">아직 제출 기록이 없습니다.</p>'; }
function renderMembers() { const list = $('memberList'); list.innerHTML = ''; if (!members.length) list.innerHTML = '<p class="empty-box">등록된 회원이 없습니다.</p>'; members.forEach(member => { const row = $('memberTemplate').content.firstElementChild.cloneNode(true); row.dataset.id = member.id; row.querySelector('.member-name').value = member.name; row.querySelector('.member-aliases').value = member.aliases.join('|'); list.appendChild(row); }); renderSubmitterOptions(); }
function commitMemberInputs() { document.querySelectorAll('.member-row').forEach(row => { const member = members.find(m => m.id === row.dataset.id); if (!member) return; member.name = row.querySelector('.member-name').value.trim(); member.aliases = row.querySelector('.member-aliases').value.split(/[|,;]/).map(v => v.trim()).filter(Boolean); }); saveMembers(); renderSubmitterOptions(); renderHistory(); }
function parseCsvLine(line) { const fields = []; let field = ''; let quoted = false; for (let i = 0; i < line.length; i++) { const c = line[i]; if (c === '"' && line[i + 1] === '"' && quoted) { field += '"'; i++; } else if (c === '"') quoted = !quoted; else if (c === ',' && !quoted) { fields.push(field.trim()); field = ''; } else field += c; } fields.push(field.trim()); return fields; }
function parseMembersCsv(input) { return String(input).replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n').split('\n').map(x => x.trim()).filter(Boolean).map(parseCsvLine).filter(x => x[0] && x[0] !== '이름').map(x => ({ id: newId(), name: x[0], aliases: (x[1] || '').split(/[|;]/).map(v => v.trim()).filter(Boolean) })); }
function csvDownload(name, rows) { const quote = value => `"${String(value ?? '').replaceAll('"', '""')}"`; const blob = new Blob(['\uFEFF' + rows.map(row => row.map(quote).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
function submit(event) { event.preventDefault(); const memberId = $('submitter').value; const date = $('submissionDate').value; const url = $('resultUrl').value.trim(); const note = $('submissionNote').value.trim(); if (!memberId || !date || !url) { showNotice('회원 이름, 제출 날짜, 결과물 링크를 모두 입력해 주세요.'); return; } try { new URL(url); } catch { showNotice('결과물 링크는 https:// 또는 http:// 주소로 입력해 주세요.'); return; } const old = submissions.find(s => s.memberId === memberId && s.date === date); const record = { id: old?.id || newId(), memberId, date, url, note, submittedAt: old?.submittedAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; submissions = old ? submissions.map(s => s.id === old.id ? record : s) : [...submissions, record]; saveSubmissions(); $('historyDate').value = date; $('resultUrl').value = ''; $('submissionNote').value = ''; showNotice(old ? '기존 제출 기록을 새 링크로 업데이트했습니다.' : '제출 기록을 남겼습니다.', 'success'); renderHistory(); }

$('todayLabel').textContent = `오늘 ${dateKey()}`; $('submissionDate').value = dateKey(); $('historyDate').value = dateKey(); renderMembers(); renderHistory();
document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(x => x.classList.toggle('active', x === tab)); document.querySelectorAll('.view').forEach(x => x.classList.toggle('active-view', x.id === tab.dataset.tab)); if (tab.dataset.tab === 'history') renderHistory(); }));
$('submissionForm').addEventListener('submit', submit); $('historyDate').addEventListener('change', renderHistory); $('memberList').addEventListener('input', commitMemberInputs);
$('addMemberBtn').addEventListener('click', () => { members.push({ id: newId(), name: '새 회원', aliases: [] }); saveMembers(); renderMembers(); });
$('memberList').addEventListener('click', e => { if (!e.target.classList.contains('remove-member')) return; members = members.filter(m => m.id !== e.target.closest('.member-row').dataset.id); saveMembers(); renderMembers(); renderHistory(); });
$('importMembersBtn').addEventListener('click', () => $('memberFileInput').click()); $('memberFileInput').addEventListener('change', async e => { const file = e.target.files[0]; if (!file) return; const imported = parseMembersCsv(await file.text()); if (!imported.length) { showNotice('가져올 회원이 없습니다.'); return; } members = imported; saveMembers(); renderMembers(); renderHistory(); showNotice(`${imported.length}명의 회원을 가져왔습니다.`, 'success'); e.target.value = ''; });
$('exportMembersBtn').addEventListener('click', () => csvDownload('회원_명단.csv', [['이름', '별칭'], ...members.map(m => [m.name, m.aliases.join('|')])])); $('exportSubmissionsBtn').addEventListener('click', () => csvDownload('과제_제출_기록.csv', [['날짜', '회원', '결과물 링크', '메모', '제출시각'], ...submissions.map(s => [s.date, memberName(s.memberId), s.url, s.note, formatDateTime(s.submittedAt)])]));
$('copyMissingBtn').addEventListener('click', async () => { const day = $('historyDate').value; const missing = members.filter(m => !submissions.some(s => s.memberId === m.id && s.date === day)).map(m => m.name); const [, month, date] = day.split('-'); const text = `[${Number(month)}/${Number(date)} 과제 미제출] ${missing.join(', ')} — 확인 부탁드립니다`; try { await navigator.clipboard.writeText(text); showNotice('미제출자 명단을 복사했습니다.', 'success'); } catch { showNotice('클립보드 복사에 실패했습니다.'); } });
